version: "3.8"
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
    networks:
      - net1
  nextjs:
    container_name: nextjs
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - net1


networks:
  net1:
    driver: bridge
