name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: copy file via ssh password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            whoami
            cd ${{ secrets.DEPLOY_DIR }}
            sudo docker compose down
            sudo docker kill $(docker ps -aq) && docker rm $(docker ps -aq)
            sudo docker system prune -af --volumes
            sudo git pull origin main
            echo "${{ secrets.ENV_FILE }}" > ./.env
            sudo docker compose up --build -d
